services:
  - type: web
    name: vanguard-backend
    env: node
    repo: https://github.com/Corptech02/vanguard-insurance.git
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: GMAIL_CLIENT_ID
        sync: false
      - key: GMAIL_CLIENT_SECRET
        sync: false