services:
  - type: web
    name: vanguard-insurance
    runtime: python
    buildCommand: "echo 'No build needed'"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    autoDeploy: true